version: "2"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodbData:/data/db

  backoffice:
    image: jordillaveria/backoffice:latest
    container_name: backoffice
    ports:
      - 4000:80

  #   webApp:
  #     build: #tbd
  #     image: webApp:latest
  #     container_name: webApp
  #     ports:
  #       - 4001:80
  #     environment:
  #       - VIRTUAL_HOST=eaweb.chickenkiller.com
  #       - LETSENCRYPT_HOST=eaweb.chickenkiller.com

  api:
    image: jordillaveria/api:latest
    container_name: api
    ports:
      - 3000:3000

volumes:
  mongodbData:
