name: GitHub Actions Demo
on:   
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
            node-version: 4
      - run: npm install

      - name: Super-Linter
        uses: github/super-linter@v4.9.2
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm test


      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
            image: jordillaveria/seminari-12
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

