name: GitHub Actions Demo
on:   
  push:
    branches: 
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
            node-version: 4
      - name: Super-Linter
        uses: github/super-linter@v4.9.2
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
